import type { Metadata } from "next";
import "@/assets/preset_styles.css";

import Navbar from "@/app/Navbar/navbar";
import ClickSpark from "../components/ClickSpark";
import GlobalSearch from "@/my_components/miniSearchComp/miniSearch";
import { TSQueryProvider } from "@/DataAccessLayer/tanstack_DAL";


export const metadata: Metadata = {
	title: "Khisponi",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {


	return (
		<html lang="en">
			<body className="antialiased">
				<TSQueryProvider>
				{/* Search component rendered out of flex flow */}
				<GlobalSearch />
				<Navbar />
				<main className="w-full bg-primary">
					<ClickSpark
						sparkColor="#777777"
						sparkSize={10}
						sparkRadius={145}
						sparkCount={12}
						duration={1100}
					>
						<div className="w-full">{children}</div>
					</ClickSpark>
				</main>
				</TSQueryProvider>
			</body>
		</html>
	);
}