import type { Metadata } from "next";
// import "./globals.css";
import "../assets/dx-components-theme.css";
import "../assets/preset_root.css";
import "../assets/flexing.css";
import "../assets/patterns.css";
import Navbar from "@/my_components/Navbar/navbar";

export const metadata: Metadata = {
	title: "Khisponi",
	// icons: "./knowledge.svg",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<Navbar></Navbar>
			<body>
				<main>{children}</main>
			</body>
		</html>
	);
}
